name: Get Kubernetes Pods

on:
  workflow_dispatch:  # Allows manual trigger from the GitHub Actions UI

jobs:
  get-pods:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.0'  # Match your cluster version

    - name: Configure kubectl with kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

    - name: Get Pods
      run: |
        kubectl get pods
